README.md
docs/UserGuide.md

Readme updated, but still need the UI

Updated Readme

---

src/main/java/seedu/address/Main.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/RemarkCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Remark.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Tutorial adding command

---

docs/team/jingting1412.md

Changed branch name. Fixes #37

Add skeletal PPP

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/exceptions/CommandException.java

Changed branch name. Closes #17

Update dg non functional requirements glossary

---

docs/DeveloperGuide.md

Update DG: Use cases

---

docs/DeveloperGuide.md
docs/index.md

Update DG to personalize to our app

---

build.gradle

Repaired the gradle file

---

src/main/java/seedu/staffsnap/commons/util/StringUtil.java
src/main/java/seedu/staffsnap/logic/commands/FindCommand.java
src/main/java/seedu/staffsnap/model/applicant/NameContainsKeywordsPredicate.java
src/test/java/seedu/staffsnap/commons/util/StringUtilTest.java
src/test/java/seedu/staffsnap/logic/commands/FindCommandTest.java
src/test/java/seedu/staffsnap/model/applicant/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/staffsnap/testutil/TypicalApplicants.java

Find applicant

---

src/main/java/seedu/staffsnap/logic/commands/AddCommand.java
src/main/java/seedu/staffsnap/logic/parser/ParserUtil.java
src/main/java/seedu/staffsnap/model/applicant/Applicant.java
src/test/java/seedu/staffsnap/logic/parser/ParserUtilTest.java
src/test/java/seedu/staffsnap/model/applicant/ApplicantTest.java

Update add applicant command

---

src/main/java/seedu/staffsnap/logic/parser/DeleteCommandParser.java
src/test/java/seedu/staffsnap/logic/parser/DeleteCommandParserTest.java

Update testcases for DeleteCommandParser

---

build.gradle

Enable assertions with Gradle build

---

src/main/java/seedu/staffsnap/logic/Messages.java
src/main/java/seedu/staffsnap/logic/commands/AddInterviewCommand.java
src/main/java/seedu/staffsnap/logic/commands/DeleteInterviewCommand.java
src/main/java/seedu/staffsnap/logic/commands/EditCommand.java
src/main/java/seedu/staffsnap/logic/commands/EditInterviewCommand.java
src/main/java/seedu/staffsnap/logic/parser/AddCommandParser.java
src/main/java/seedu/staffsnap/model/applicant/Applicant.java
src/main/java/seedu/staffsnap/model/applicant/CustomFilterPredicate.java
src/main/java/seedu/staffsnap/model/applicant/Score.java
src/main/java/seedu/staffsnap/model/util/SampleDataUtil.java
src/main/java/seedu/staffsnap/storage/JsonAdaptedApplicant.java
src/main/java/seedu/staffsnap/ui/ApplicantCard.java
src/main/resources/view/DarkTheme.css
src/test/java/seedu/staffsnap/logic/commands/EditApplicantDescriptorTest.java
src/test/java/seedu/staffsnap/model/applicant/ScoreTest.java
src/test/java/seedu/staffsnap/storage/JsonAdaptedApplicantTest.java
src/test/java/seedu/staffsnap/testutil/ApplicantBuilder.java
src/test/java/seedu/staffsnap/testutil/TypicalApplicants.java

Add applicant score

---

src/main/java/seedu/staffsnap/logic/commands/ClearCommand.java

Add assertions

---

docs/UserGuide.md

Update UG - FAQ and glossary

---

docs/team/craigtonlian.md

Update PPP with RepoSense

---

src/main/java/seedu/staffsnap/model/applicant/Email.java
src/main/java/seedu/staffsnap/model/applicant/Position.java

Closes #148, #149, #172, #173, #175

Fix error message typo

---

docs/UserGuide.md
src/main/java/seedu/staffsnap/logic/commands/ImportCommand.java

Closes #156
Closes #163 
Closes #174
Closes #183

Fix ImportCommand duplicate applicant bug and UG bugs

---

src/main/java/seedu/staffsnap/logic/parser/StatusCommandParser.java
src/test/java/seedu/staffsnap/logic/parser/StatusCommandParserTest.java

Fix status command bug

---

docs/UserGuide.md

Fix typo in example command for filter

---

docs/UserGuide.md
src/main/java/seedu/staffsnap/logic/commands/FindCommand.java
src/main/java/seedu/staffsnap/logic/parser/FindCommandParser.java
src/test/java/seedu/staffsnap/logic/commands/FindCommandTest.java
src/test/java/seedu/staffsnap/logic/parser/FindCommandParserTest.java

Debug find command

---

docs/UserGuide.md
src/main/java/seedu/staffsnap/logic/commands/FilterCommand.java
src/main/java/seedu/staffsnap/logic/parser/ParserUtil.java

Fix filter by score bug

---

src/main/java/seedu/staffsnap/logic/parser/FilterCommandParser.java
src/main/java/seedu/staffsnap/model/applicant/Score.java
src/test/java/seedu/staffsnap/logic/parser/ApplicantBookParserTest.java

Fix filter command bugs

---

docs/UserGuide.md

Closes #155 
Specified the default status as UNDECIDED. Specified max length of keywords for find is 55 characters

Improve UG according to PE feedback

---

docs/team/jingting1412.md

update ppp - jingting
